### ISSUE TITLE
Old Docker-Image referenced in DummyDataSource

### ISSUE THREAD

**Issue by MaximAstaschov** [slowproj/slowdash#2]
The docker-compose file in DummyDataSource tries to pull the image `slowdash:2402-python12` which doesn't exist. It needs to be changed to `slowproj/slowdash:2402`.

**Comment by SanshiroEnomoto** [comment]
Thank you for the report. I've changed the image name to `slowproj/slowdash:2402`. The name `-python12` was a leftover from my local testing, and the image was not pushed to the DockerHub (it was pushed to GitHub CR for testing purposes).
